### ISSUE TITLE
Reported losses don't add up

### ISSUE THREAD

**Issue by peastman** [torchmd/torchmd-net#184]
In my older training runs, the reported losses add up the way I would expect them to.  For example,

```
epoch,lr,train_loss,val_loss,train_loss_y,train_loss_dy,val_loss_y,val_loss_dy,step
0,0.0005000000237487257,1560410.75,29107.017578125,1545303.75,15106.9501953125,22439.8046875,6667.21044921875,2058
1,0.0005000000237487257,28395.6875,11338.0146484375,22872.443359375,5523.244140625,6752.93896484375,4585.07568359375,4117
2,0.0005000000237487257,21093.2890625,7725.9208984375,17048.27734375,4045.013671875,4260.59130859375,3465.329345703125,6176
3,0.0005000000237487257,14856.837890625,6906.75,11753.6455078125,3103.19287109375,4210.92578125,2695.82421875,8235
```

On each row, `train_loss_y`+`train_loss_dy`=`train_loss`.

But I've just been doing a training run with the new TensorNet code, and they don't add up:

```
epoch,lr,train_loss,val_loss,train_loss_y,train_loss_neg_dy,val_loss_y,val_loss_neg_dy,step
0.0,0.0005000000237487257,2974542.0,17496.51171875,5931663.0,17421.421875,32104.94921875,2888.073974609375,8239
1.0,0.0005000000237487257,9010.119140625,4716.5751953125,15454.5888671875,2565.650146484375,7229.13916015625,2204.01220703125,16479
2.0,0.0005000000237487257,5584.4951171875,5571.8486328125,9334.0888671875,1834.90234375,9795.0322265625,1348.665771484375,24719
3.0,0.0005000000237487257,4905.42138671875,2246.763916015625,8251.9189453125,1558.9232177734375,3322.157958984375,1171.3697509765625,32959
```

In this case, `train_loss_y`+`train_loss_neg_dy`=`2*train_loss`.  Has something changed in how they're reported?  Is the total loss half as large as it should be, or are the components twice as large as they should be?

**Comment by RaulPPelaez** [comment]
Is this something you are seeing only for TensorNet?

**Comment by guillemsimeon** [comment]
To the best of my knowledge, `train_loss_y` and `train_loss_dy` are stored before training weights are applied, and `train_loss` is stored afterwards 
https://github.com/torchmd/torchmd-net/blob/237b4fe1bf0ce52721b42fe51f35efca018753f9/torchmdnet/module.py#L130-L136
It could be that in your previous training you were using both weights equal to 1. Since for TensorNet you are probably using 0.5 for both weights, you need to apply the factor 0.5 to both energy and force losses to recover `train_loss`, which is stored once the weights have been applied. A quick check would be to run both ET and TensorNet with both weights equal to 1, and both weights equal to 0.5.

**Comment by guillemsimeon** [comment]
Also, I have just noticed that for forces you have the old label `dy`. It was changed to `neg_dy` a while ago.

**Comment by peastman** [comment]
You're right, I was using the config file you provided, which has scales of 0.5 for both of them.  That explains it!
